name: My first github action 
on: [push]
jobs:
  build-app:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install node_modules
        run: npm install
      - name: Build Project
        run: npm run build
      - name: Finish Build
        run: echo "Build Finish Successfully!!" 