name: My first github action 
on: [push]
jobs:
  buildApp:
    name: Build Project
    runs-on: ubuntu-latest
    outputs:
      text: ${{ steps.finished.outputs.text }}
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install node_modules
        run: npm install
      - name: Build Project
        run: npm run build
      - name: sets the vercel
        run: |
          cd build
          mkdir .vercel
          cd .vercel
          touch project.json
          echo "{\"projectId\":\"$VERCEL_PROJECT_ID\",
          \"orgId\":\"$VERCEL_ORG_ID\"}" > project.json
      - name: Deploying Project
        run: npm run deploy
      - name: setup finish
        id: finished
        run: echo "::set-output 
          name=text::hello-world-from-build-job"
  test-app:
    name: Test Project
    needs: buildApp
    runs-on: ubuntu-latest
    env:
      MY_JOB_OUTPUT: ${{ needs.buildApp.outputs.text }}
    steps:
      - name: Test project app
        run: echo "Testing Done"