name: My first github action 
on: [push]
jobs:
  build-app:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install node_modules
        run: npm install
      - name: Build Project
        run: npm run build
      - name: Deploying Project
        env:
          VERCEL_ORG_ID: CFmuuMcCE2Gig8j7H59sdEBS
          VERCEL_PROJECT_ID: prj_6wlHfFXuW1anSBjnQKRYSEPVQ5hE
        run: npm deploy
      - name: setup finish  
        run: echo "Setup Finish"